### ISSUE TITLE
"Pam's HarvestCraft 2 - Crops" Compatibility

### ISSUE THREAD

**Issue by wsxiya** [Su5eD/Lazurite#1]
![4(DL`I%{CKG~KI`7GG 3$LO](https://github.com/Su5eD/Lazurite/assets/114494454/1903fc83-cc8c-4131-86b3-2ef916fe47ae)

**Comment by Su5eD** [comment]
This happened due to a bug in FFAPI, which has now been fixed in version [0.90.4+1.9.30+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.90.4+1.9.30+1.20.1).
