### ISSUE TITLE
[Connector/Embeddium] Missing support for the FREX Flawless Frames API for Replay Mod.

### ISSUE THREAD

**Issue by VOLKOUL** [Su5eD/Lazurite#11]
### Details:

https://github.com/embeddedt/embeddium/issues/241
https://github.com/Sinytra/Connector/issues/932

**Comment by Wanderer70** [comment]
yay!

**Comment by VOLKOUL** [comment]
**It's the same thing with Lazurite 1.0.4, the patch didn't seem to fix the issue.**

Could it be that because it's Lazurite and not Embeddium that got support for the FREX Flawless Frames API, Replay Mod doesn't "recognise" said API's presence? Since, you know, Replay Mod searches for the API in Sodium and because Embeddium replaces Sodium it would make sense for Replay Mod to search for the API in Embeddium exclusively, instead of scanning other mods such as Lazurite.

If so, I wonder weather this could be fixed the same way people got NVIDIUM to work on Connector? I mean editing the "connector.json" and "fabric_loader_dependencies.json" files. Or perhaps it doesn't work due to this exact reason? (for me, at least) Currently, I have these config files edited to make NVIDIUM work, which implies that I have tinkered with how Sodium is viewed/related to the game. Here's the contents of the previously mentioned files, in case they turn out to be important:

**connector.json :**

{
  "version": 1,
  "hiddenMods": [],
  "globalModAliases": {
    "cloth_config": "cloth-config2",
    "playeranimator": "player-animator",
    "embeddium": ["sodium"]
  }
}

**fabric_loader_dependencies.json :**

{
"version": 1,
"overrides":{
"nvidium":{
"-depends":{
"sodium": "IGNORED"
},
"+depends":{
"sodium": "*"
}
}
}
}

**Comment by VOLKOUL** [comment]
Fixed it. Even with the Lazurite update I couldn't render anything, but after making a fresh installation I noticed that everything worked fine. There probably was some breaking change in an Embeddium update that altered the config file in some way. Anyway, I deleted all config files so that they could generate again and everything works perfectly!
