### ISSUE TITLE
[1.20.1] Using Replay Mod through Sinytra Connector produces videos with GUI overlay even with Lazurite installed.

### ISSUE THREAD

**Issue by VOLKOUL** [Su5eD/Lazurite#4]
### Describe the bug

This happens only when Embeddium or Rubidium is installed. (I have reported this to them too and it seems it has something to do with the Fabric Rendering API). I assume Lazurite intends to fix such stuff, but it does not help in this case.

### Steps to reproduce

1. Install Connector, Connector Extras, Forgified Fabric API, Replay Mod and Embeddium (and Lazurite)
2. Launch the game and record something
3. Open replay viewer, set up a camera path and make a video
  
The result will be something like this:

https://github.com/Su5eD/Lazurite/assets/97387920/90ee8443-41c0-4fe9-a4a1-07e5ccfa8460

### Logs

Not a crash

### Additional context

This is not OBS, but an actual Replay Mod video. It should not have the GUI on top

**Comment by Su5eD** [comment]
Does this happen without Lazurite installed?

**Comment by VOLKOUL** [comment]
Yes, both with and without.

**Comment by Su5eD** [comment]
Okay, then I'll move this over to Connector's repo

**Comment by Su5eD** [comment]
Nevermind, github only allows that within the same org namespace...
