### ISSUE TITLE
Visual bug with superbettergrass(snow textures) with shaders

### ISSUE THREAD

**Issue by kakashi1464** [Su5eD/Lazurite#6]
### Describe the bug

Visual bug with superbettergrass with shaders

### Steps to reproduce

1. Install embeddium, lazurite, oculus, Synitra Connector, ffapi and superbettergrass
2. Run minecraft with shaders
3. See visual bug with snow

### Logs

[latest.log](https://mclo.gs/3kDd3vX)
[debug.log](https://mclo.gs/I7glQL3)

### Additional context

![image](https://github.com/Su5eD/Lazurite/assets/126709049/bbc3c6d3-35ef-4268-af2a-7a05173d7e90)

**Comment by kakashi1464** [comment]
doesn't occur without  embeddium and lazurite

**Comment by Su5eD** [comment]
> Run minecraft with shaders

What shaders are you using?

**Comment by kakashi1464** [comment]
Complementary Reimagined

**Comment by kakashi1464** [comment]
Ok

**Comment by Tapacywka** [comment]
Can reproduce this bug without SBG, but with Fast Better Grass Resourcepack. For both Complementary Reimagined and Complementary Unbound.

**Comment by BLovegrove** [comment]
can confirm, I'm getting the same issue - seems PBR related, as disabling that makes the issue disappear

**Comment by BLovegrove** [comment]
not planned? huh? so this just isn't getting fixed? Could we get some clarification on this? Given that multiple people have been able to reproduce it now and removing this mod in particular fixes the issue means surely this is something to look into?
