### ISSUE TITLE
Not working with embeddium-0.3.0

### ISSUE THREAD

**Issue by SeanChengN** [Su5eD/Lazurite#7]
### Describe the bug

Unable to launch game when embeddium is updated to 0.3.0

### Steps to reproduce

1. update embeddium to 0.3.0
2. launch game

### Logs

https://pastebin.com/0S5ZW1PH

**Comment by SaltSouls** [comment]
This is an issue with Lazurites dependencies not being set up to work with the latest version.

**Comment by AsheX1** [comment]
it does work on embeddium-0.3.0 but it needs a work around gone try a second work around now to see if that also works in the mean time take this jar 

DELETED just use the normel embeddium jar from embeddedt

this version of embeddium show ingame as  0.2.18 but its 0.3.0 i edited the mods.toml from this jar now gone see if i can just remove the version check from Lazurite

**Comment by AsheX1** [comment]
even better just use this lazurite jar i remove the dependencies and now it works with the normal embeddium 0.3.0 jar
[lazurite-1.0.1+mc1.20.1.zip](https://github.com/Su5eD/Lazurite/files/14102930/lazurite-1.0.1%2Bmc1.20.1.zip)

**Comment by Su5eD** [comment]
Fixed by #8
